title: Generic Page
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          fields:
             header.primaryImage:
              ordering: 2
              type: file
              label: 'Primary Image'
              multiple: false
              destination: '@self'
              accept:
                - image/*
